import { createClient } from '@supabase/supabase-js'

export const supabase = createClient(
  'https://erhumtzfyarckjowgvcd.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaHVtdHpmeWFyY2tqb3dndmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MjE2NjksImV4cCI6MjA4ODk5NzY2OX0.ydqd0vNsDNgnzNjFqkqUrya8oIz-fV2KOlISKmt4O00'
)

export const PLANS = [
  {
    slug: 'hotel',
    name: 'Hôtel',
    icon: '🏨',
    desc: 'Chambres, réservations, check-in/out',
    features: ['Gestion des chambres par type', 'Réservations & check-in/out', 'Agenda hôtel', 'Portail client intégré'],
    price_monthly: 49,
    price_yearly: 470,
    color: '#4a7fa5',
    stripe_monthly: 'price_1TApjCAwXHAGgOa46qe5SRiL',
    stripe_yearly:  'price_1TApjFAwXHAGgOa4onHPGU6y',
  },
  {
    slug: 'restaurant',
    name: 'Restaurant',
    icon: '🍽️',
    desc: 'Tables, menu, ordres, réservations',
    features: ['Plan de salle interactif', 'Gestion des commandes', 'Menu & catégories', 'Réservations en ligne'],
    price_monthly: 39,
    price_yearly: 374,
    color: '#4a9070',
    stripe_monthly: 'price_1TApjIAwXHAGgOa41C5uRpLR',
    stripe_yearly:  'price_1TApjMAwXHAGgOa4DugcxXIQ',
  },
  {
    slug: 'spa',
    name: 'Spa & Wellness',
    icon: '💆',
    desc: 'Soins, piscine, jacuzzi, agenda',
    features: ['Rendez-vous & soins', 'Piscine & jacuzzi', 'Gestion du personnel', 'Réservations en ligne'],
    price_monthly: 39,
    price_yearly: 374,
    color: '#7a6fa5',
    stripe_monthly: 'price_1TApjPAwXHAGgOa4f2oPMvKh',
    stripe_yearly:  'price_1TApknAwXHAGgOa4kklpZNtF',
  },
  {
    slug: 'padel',
    name: 'Padel',
    icon: '🎾',
    desc: 'Terrains, créneaux, réservations',
    features: ['Gestion des terrains', 'Créneaux & planning', 'Réservations en ligne', 'Statistiques & rapports'],
    price_monthly: 29,
    price_yearly: 278,
    color: '#a07a30',
    stripe_monthly: 'price_1TApkrAwXHAGgOa4I5p1EHDb',
    stripe_yearly:  'price_1TApkuAwXHAGgOa4mdTgO7sc',
  },
  {
    slug: 'all',
    name: 'All Inclusive',
    icon: '⭐',
    desc: 'Tous les modules — économisez 20%',
    features: ['Hôtel + Restaurant + Spa + Padel', 'Facturation unifiée', 'Rapports consolidés', 'Support prioritaire'],
    price_monthly: 129,
    price_yearly: 1238,
    color: '#c9a030',
    stripe_monthly: 'price_1TApkyAwXHAGgOa4nsJNdX08',
    stripe_yearly:  'price_1TApl0AwXHAGgOa4aujRgxp6',
    highlight: true,
  },
]
